index:
    path: /
    controller: App\Controller\ArticlesController::showAll

article_show:
    path: /article/{id}
    controller: App\Controller\ArticlesController::show

donate:
    path: /donate
    controller: App\Controller\DonateController::donate

author:
    path: /author
    controller: App\Controller\AuthorController::author


